#!/usr/bin/env python3
"""
APA-style threshold-dependent SCAFFOLD scalability figures.

This script PLOTS threshold-dependent results that were already generated by
the validation-based threshold evaluation pipeline. It does not select a model,
round, or threshold and does not optimize anything on the test set.

Expected default input
----------------------
result/splits_iid_scaling/final_threshold_analysis/SCAFFOLD/
    all_threshold_results.csv

Alternatively, pass the analysis directory itself. The script then reads all:

    splits_iid_<N>_clients/run_<r>/threshold_results.json

Important
---------
The threshold-independent files under:

    result/splits_iid_scaling/final_test_set_eval/SCAFFOLD/

such as test_metrics.json and test_summary.json are not sufficient for these
plots because they do not contain the two validation-selected operating points.

Generated figures
-----------------
Figure 1: MCC-optimal operating point
    A. Validation-selected decision threshold
    B. Test MCC
    C. Test recall and specificity

Figure 2: Fixed minimum-recall operating point
    A. Validation-selected decision threshold
    B. Test recall and specificity with the prespecified validation-recall reference

Design
------
* same UHH-based colors, font sizes, axes, markers, and spacing as the
  threshold-independent thesis figures
* no decorative titles inside the figures
* bold panel labels A-C only
* small gray points for individual runs
* colored circles and lines for means across five repeated runs
* one shared neutral legend below each figure
* base-2 logarithmic client axis
* PDF and high-resolution PNG output
* suggested APA captions written to a text file

Example
-------
python plot-thr-dependent-scaffold.py

python plot-thr-dependent-scaffold.py \
    --input result/splits_iid_scaling/final_threshold_analysis/SCAFFOLD

python plot-thr-dependent-scaffold.py \
    --input result/splits_iid_scaling/final_threshold_analysis/SCAFFOLD/all_threshold_results.csv \
    --output-dir result/splits_iid_scaling/final_threshold_analysis/SCAFFOLD/apa_figures
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any, Dict, Iterable, List, Mapping, Optional, Sequence, Tuple

import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib.font_manager import findfont
from matplotlib.lines import Line2D
from matplotlib.ticker import FuncFormatter, MaxNLocator
import numpy as np
import pandas as pd


# =============================================================================
# DEFAULTS
# =============================================================================
DEFAULT_ANALYSIS_ROOT = Path(
    "result/splits_iid_scaling/final_threshold_analysis/SCAFFOLD"
)
DEFAULT_INPUT = DEFAULT_ANALYSIS_ROOT / "all_threshold_results.csv"
DEFAULT_OUTPUT_DIR = DEFAULT_ANALYSIS_ROOT / "apa_threshold_figures"

DEFAULT_STRATEGY = "SCAFFOLD"
EXPECTED_RUNS = 5
EXPECTED_SCALING_POINTS = 14
DEFAULT_FORMATS: Tuple[str, ...] = ("pdf", "png")
PNG_DPI = 300
FIGURE_WIDTH = 12.0

SCALING_POINTS: Tuple[int, ...] = (
    2,
    4,
    8,
    16,
    32,
    64,
    128,
    256,
    512,
    1024,
    2048,
    4096,
    8192,
    16384,
)

# Match the visual language of the threshold-independent figures.
LINE_WIDTH = 1.80
MARKER_SIZE = 3.00
MARKER_EDGE_WIDTH = 0.50
INDIVIDUAL_POINT_SIZE = 12
GRID_ALPHA = 0.22
GRID_LINEWIDTH = 0.55

UHH_RED = "#E2001A"
UHH_BLUE = "#0271BB"
UHH_SLATE = "#3B515B"
INK = "#202124"
REFERENCE_GRAY = "#6B7280"
INDIVIDUAL_RUN_GRAY = "#9AA0A6"
SHARED_LEGEND_GRAY = UHH_SLATE

THRESHOLD_COLOR = UHH_SLATE
MCC_COLOR = UHH_RED
RECALL_COLOR = UHH_BLUE
SPECIFICITY_COLOR = UHH_RED

REQUIRED_COLUMNS = {
    "strategy",
    "scaling_point",
    "run",
    "threshold_regime",
    "selected_threshold",
    "test_mcc",
    "test_recall",
    "test_specificity",
}

JSON_SCALING_RE = re.compile(r"splits_iid_(\d+)_clients$")


# =============================================================================
# ARGUMENTS AND STYLE
# =============================================================================
def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Create APA-style threshold-dependent SCAFFOLD scalability figures "
            "from validation-selected threshold results."
        )
    )
    parser.add_argument(
        "--input",
        type=Path,
        default=DEFAULT_INPUT,
        help=(
            "all_threshold_results.csv or the final_threshold_analysis/SCAFFOLD "
            f"directory (default: {DEFAULT_INPUT})"
        ),
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help=f"Output directory (default: {DEFAULT_OUTPUT_DIR})",
    )
    parser.add_argument(
        "--strategy",
        default=DEFAULT_STRATEGY,
        help=f"Strategy to retain (default: {DEFAULT_STRATEGY})",
    )
    parser.add_argument(
        "--expected-runs",
        type=int,
        default=EXPECTED_RUNS,
        help=f"Expected runs at every scaling point (default: {EXPECTED_RUNS})",
    )
    parser.add_argument(
        "--expected-scaling-points",
        type=int,
        default=EXPECTED_SCALING_POINTS,
        help=(
            "Expected scaling points for each threshold regime "
            f"(default: {EXPECTED_SCALING_POINTS})"
        ),
    )
    parser.add_argument(
        "--formats",
        nargs="+",
        choices=("pdf", "png", "svg", "tiff"),
        default=list(DEFAULT_FORMATS),
        help="Output formats (default: pdf png)",
    )
    parser.add_argument(
        "--font",
        default="Arial",
        help="Preferred sans-serif font (default: Arial)",
    )
    parser.add_argument(
        "--width",
        type=float,
        default=FIGURE_WIDTH,
        help=f"Figure width in inches (default: {FIGURE_WIDTH})",
    )
    return parser.parse_args()


def available_font(preferred: str) -> str:
    for candidate in (preferred, "Liberation Sans", "DejaVu Sans"):
        try:
            findfont(candidate, fallback_to_default=False)
            return candidate
        except ValueError:
            continue
    return "DejaVu Sans"


def configure_matplotlib(font_name: str) -> None:
    mpl.rcParams.update(
        {
            "font.family": font_name,
            "font.size": 10.5,
            "axes.labelsize": 12.0,
            "axes.titlesize": 12.0,
            "xtick.labelsize": 10.5,
            "ytick.labelsize": 10.5,
            "legend.fontsize": 9.2,
            "axes.linewidth": 0.90,
            "axes.edgecolor": INK,
            "axes.labelcolor": INK,
            "xtick.color": INK,
            "ytick.color": INK,
            "text.color": INK,
            "figure.facecolor": "white",
            "axes.facecolor": "white",
            "savefig.facecolor": "white",
            "savefig.edgecolor": "white",
            "savefig.bbox": "tight",
            "savefig.pad_inches": 0.05,
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
            "svg.fonttype": "none",
        }
    )


# =============================================================================
# INPUT
# =============================================================================
def finite_float(value: Any) -> float:
    number = float(value)
    if not np.isfinite(number):
        raise ValueError(f"Non-finite numeric value: {value!r}")
    return number


def flatten_threshold_json(path: Path) -> List[Dict[str, Any]]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"Expected JSON object in {path}")

    strategy = str(payload.get("strategy", DEFAULT_STRATEGY))
    scaling_point = int(payload["scaling_point"])
    run = int(payload["run"])

    rows: List[Dict[str, Any]] = []
    regime_map = (
        ("mcc_optimal", "mcc_optimal"),
        ("minimum_recall", "minimum_recall"),
    )

    for json_key, regime in regime_map:
        section = payload.get(json_key)
        if not isinstance(section, dict):
            raise KeyError(f"Missing '{json_key}' object in {path}")

        validation = section.get("validation_selection")
        test = section.get("test_evaluation")
        if not isinstance(validation, dict) or not isinstance(test, dict):
            raise KeyError(
                f"Missing validation_selection or test_evaluation in "
                f"{path}: {json_key}"
            )

        row: Dict[str, Any] = {
            "strategy": strategy,
            "scaling_point": scaling_point,
            "run": run,
            "threshold_regime": regime,
            "selected_threshold": validation.get("threshold"),
            "validation_mcc": validation.get("mcc"),
            "validation_recall": validation.get("recall"),
            "validation_specificity": validation.get("specificity"),
            "test_mcc": test.get("mcc"),
            "test_recall": test.get("recall"),
            "test_specificity": test.get("specificity"),
            "test_precision": test.get("precision"),
            "test_f1": test.get("f1"),
            "test_balanced_accuracy": test.get("balanced_accuracy"),
            "test_false_positive_rate": test.get("false_positive_rate"),
            "test_false_positives_per_1000_negatives": test.get(
                "false_positives_per_1000_negatives"
            ),
            "source_json": str(path),
        }

        if regime == "minimum_recall":
            row["minimum_validation_recall_requirement"] = validation.get(
                "minimum_recall"
            )

        rows.append(row)

    return rows


def read_json_tree(root: Path) -> pd.DataFrame:
    files = sorted(root.glob("splits_iid_*_clients/run_*/threshold_results.json"))
    if not files:
        files = sorted(root.rglob("threshold_results.json"))
    if not files:
        raise FileNotFoundError(
            f"No threshold_results.json files found under:\n  {root}"
        )

    rows: List[Dict[str, Any]] = []
    for path in files:
        rows.extend(flatten_threshold_json(path))
    return pd.DataFrame.from_records(rows)


def read_input(path: Path) -> pd.DataFrame:
    if path.is_file():
        if path.suffix.lower() != ".csv":
            raise ValueError(
                "The input file must be all_threshold_results.csv. "
                "Alternatively pass the directory containing threshold_results.json."
            )
        return pd.read_csv(path)

    if path.is_dir():
        csv_path = path / "all_threshold_results.csv"
        if csv_path.is_file():
            return pd.read_csv(csv_path)
        return read_json_tree(path)

    # Helpful automatic fallback when the default CSV has not been written but
    # its parent contains the per-run threshold_results.json files.
    if path.name == "all_threshold_results.csv" and path.parent.is_dir():
        return read_json_tree(path.parent)

    raise FileNotFoundError(
        f"Threshold-dependent input not found:\n  {path}\n\n"
        "The threshold-independent final_test_set_eval/test_summary.json files "
        "cannot be used for validation-based threshold plots."
    )


def normalize_and_validate(
    data: pd.DataFrame,
    strategy: str,
    expected_runs: int,
    expected_scaling_points: int,
) -> pd.DataFrame:
    missing = REQUIRED_COLUMNS - set(data.columns)
    if missing:
        raise ValueError(
            "Input is missing required threshold-dependent columns:\n  "
            + "\n  ".join(sorted(missing))
        )

    frame = data.copy()
    frame["strategy"] = frame["strategy"].astype(str)
    frame["threshold_regime"] = (
        frame["threshold_regime"]
        .astype(str)
        .str.strip()
        .str.lower()
        .replace(
            {
                "maximum_validation_mcc": "mcc_optimal",
                "maximum_mcc": "mcc_optimal",
                "recall_constrained": "minimum_recall",
                "fixed_recall": "minimum_recall",
            }
        )
    )

    numeric_columns = [
        "scaling_point",
        "run",
        "selected_threshold",
        "test_mcc",
        "test_recall",
        "test_specificity",
    ]
    optional_numeric = [
        "minimum_validation_recall_requirement",
        "validation_mcc",
        "validation_recall",
        "validation_specificity",
        "test_precision",
        "test_f1",
        "test_balanced_accuracy",
        "test_false_positive_rate",
        "test_false_positives_per_1000_negatives",
    ]

    for column in numeric_columns + [
        column for column in optional_numeric if column in frame.columns
    ]:
        frame[column] = pd.to_numeric(frame[column], errors="coerce")

    if frame[numeric_columns].isna().any().any():
        invalid = frame[frame[numeric_columns].isna().any(axis=1)]
        raise ValueError(
            "Invalid required numeric threshold results:\n"
            + invalid.head(10).to_string(index=False)
        )

    frame["scaling_point"] = frame["scaling_point"].astype(int)
    frame["run"] = frame["run"].astype(int)
    frame = frame[
        (frame["strategy"] == strategy)
        & frame["threshold_regime"].isin({"mcc_optimal", "minimum_recall"})
    ].copy()

    if frame.empty:
        raise ValueError(
            f"No MCC-optimal or minimum-recall rows found for strategy '{strategy}'."
        )

    duplicate_key = ["strategy", "scaling_point", "run", "threshold_regime"]
    duplicates = frame.duplicated(duplicate_key, keep=False)
    if duplicates.any():
        raise ValueError(
            "Duplicate run/regime rows found:\n"
            + frame.loc[duplicates, duplicate_key]
            .sort_values(duplicate_key)
            .to_string(index=False)
        )

    for regime in ("mcc_optimal", "minimum_recall"):
        subset = frame[frame["threshold_regime"] == regime]
        n_points = subset["scaling_point"].nunique()
        if n_points != expected_scaling_points:
            raise ValueError(
                f"{regime}: expected {expected_scaling_points} scaling points, "
                f"found {n_points}."
            )

        run_counts = subset.groupby("scaling_point")["run"].nunique()
        incorrect = run_counts[run_counts != expected_runs]
        if not incorrect.empty:
            details = ", ".join(
                f"{int(clients)} clients: n={int(count)}"
                for clients, count in incorrect.items()
            )
            raise ValueError(
                f"{regime}: expected {expected_runs} runs at every point; {details}."
            )

    observed = sorted(frame["scaling_point"].unique().tolist())
    if tuple(observed) != SCALING_POINTS:
        print(
            "Warning: observed scaling points differ from the default sequence:\n"
            f"  {observed}"
        )

    return frame.sort_values(
        ["threshold_regime", "scaling_point", "run"]
    ).reset_index(drop=True)


# =============================================================================
# AGGREGATION
# =============================================================================
def aggregate_results(raw: pd.DataFrame) -> pd.DataFrame:
    metrics = [
        "selected_threshold",
        "test_mcc",
        "test_recall",
        "test_specificity",
    ]
    optional = [
        "validation_mcc",
        "validation_recall",
        "validation_specificity",
        "test_precision",
        "test_f1",
        "test_balanced_accuracy",
        "test_false_positive_rate",
        "test_false_positives_per_1000_negatives",
    ]
    metrics.extend(column for column in optional if column in raw.columns)

    records: List[Dict[str, Any]] = []
    grouped = raw.groupby(
        ["strategy", "threshold_regime", "scaling_point"],
        sort=True,
    )

    for (strategy, regime, clients), group in grouped:
        record: Dict[str, Any] = {
            "strategy": strategy,
            "threshold_regime": regime,
            "scaling_point": int(clients),
            "n_runs": int(group["run"].nunique()),
        }

        for metric in metrics:
            values = pd.to_numeric(group[metric], errors="coerce").dropna()
            if values.empty:
                continue
            record[f"{metric}_mean"] = float(values.mean())
            record[f"{metric}_std"] = (
                float(values.std(ddof=1)) if len(values) > 1 else 0.0
            )
            record[f"{metric}_min"] = float(values.min())
            record[f"{metric}_max"] = float(values.max())

        records.append(record)

    return pd.DataFrame.from_records(records).sort_values(
        ["threshold_regime", "scaling_point"]
    )


def get_minimum_recall_requirement(raw: pd.DataFrame) -> float:
    if "minimum_validation_recall_requirement" not in raw.columns:
        raise ValueError(
            "The minimum-recall rows do not contain "
            "'minimum_validation_recall_requirement'."
        )

    values = (
        pd.to_numeric(
            raw.loc[
                raw["threshold_regime"] == "minimum_recall",
                "minimum_validation_recall_requirement",
            ],
            errors="coerce",
        )
        .dropna()
        .unique()
    )

    if len(values) != 1:
        raise ValueError(
            "Expected one prespecified validation-recall requirement, found: "
            + ", ".join(f"{value:.6g}" for value in sorted(values))
        )
    requirement = float(values[0])
    if not (0.0 < requirement <= 1.0):
        raise ValueError(f"Invalid minimum recall requirement: {requirement}")
    return requirement


# =============================================================================
# PLOT HELPERS
# =============================================================================
def client_label(value: int) -> str:
    if value >= 1024 and value % 1024 == 0:
        return f"{value // 1024}k"
    return f"{value:,}"


def client_positions(clients: Sequence[int]) -> np.ndarray:
    return np.log2(np.asarray(clients, dtype=float))


def deterministic_jitter(count: int, span: float = 0.16) -> np.ndarray:
    if count <= 1:
        return np.zeros(count, dtype=float)
    return np.linspace(-span, span, count, dtype=float)


def set_client_axis(
    ax: plt.Axes,
    clients: Sequence[int],
    show_label: bool,
) -> None:
    positions = client_positions(clients)
    ax.set_xticks(positions)
    ax.set_xticklabels([client_label(int(value)) for value in clients])
    ax.set_xlim(float(positions.min() - 0.35), float(positions.max() + 0.35))
    ax.set_xlabel("Number of clients (log2 scale)" if show_label else "")


def style_axis(ax: plt.Axes) -> None:
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.spines["left"].set_color(INK)
    ax.spines["bottom"].set_color(INK)
    ax.spines["left"].set_linewidth(0.90)
    ax.spines["bottom"].set_linewidth(0.90)
    ax.tick_params(
        colors=INK,
        direction="out",
        labelsize=10.5,
        length=4.0,
        width=0.85,
    )
    ax.grid(True, alpha=GRID_ALPHA, linewidth=GRID_LINEWIDTH, linestyle="-")
    ax.set_axisbelow(True)


def set_panel_label(ax: plt.Axes, panel: str) -> None:
    ax.text(
        -0.075,
        1.020,
        panel,
        transform=ax.transAxes,
        ha="left",
        va="bottom",
        fontsize=12.0,
        fontweight="bold",
        color=INK,
        clip_on=False,
    )


def trimmed_decimal_formatter(max_decimals: int) -> FuncFormatter:
    def _format(value: float, _position: object) -> str:
        if not np.isfinite(value):
            return ""
        text = f"{value:.{max_decimals}f}".rstrip("0").rstrip(".")
        return "0" if text in {"", "-0"} else text

    return FuncFormatter(_format)


def padded_limits(
    values: Iterable[float],
    minimum_span: float,
    include_value: Optional[float] = None,
    padding_fraction: float = 0.12,
    hard_bounds: Optional[Tuple[float, float]] = None,
) -> Tuple[float, float]:
    array = np.asarray(list(values), dtype=float)
    array = array[np.isfinite(array)]
    if array.size == 0:
        return (0.0, 1.0)

    low = float(np.min(array))
    high = float(np.max(array))
    if include_value is not None:
        low = min(low, include_value)
        high = max(high, include_value)

    center = (low + high) / 2.0
    span = max(high - low, minimum_span)
    low = center - span / 2.0
    high = center + span / 2.0
    padding = span * padding_fraction
    low -= padding
    high += padding

    if hard_bounds is not None:
        low = max(hard_bounds[0], low)
        high = min(hard_bounds[1], high)

    if np.isclose(low, high):
        high = low + minimum_span
    return low, high


def scatter_individual_runs(
    ax: plt.Axes,
    raw: pd.DataFrame,
    clients: Sequence[int],
    metric: str,
    marker: str = "o",
    jitter_offset: float = 0.0,
    facecolor: str = INDIVIDUAL_RUN_GRAY,
    alpha: float = 0.65,
) -> List[float]:
    all_values: List[float] = []

    for clients_value in clients:
        values = (
            raw[raw["scaling_point"] == clients_value]
            .sort_values("run")[metric]
            .to_numpy(dtype=float)
        )
        x_center = float(np.log2(clients_value))
        jitter = deterministic_jitter(len(values)) + jitter_offset

        ax.scatter(
            x_center + jitter,
            values,
            s=INDIVIDUAL_POINT_SIZE,
            marker=marker,
            facecolor=facecolor,
            edgecolor="white",
            linewidth=0.35,
            alpha=alpha,
            zorder=2,
        )
        all_values.extend(values.tolist())

    return all_values


def plot_mean_line(
    ax: plt.Axes,
    aggregate: pd.DataFrame,
    metric: str,
    color: str,
    marker: str = "o",
    linestyle: str = "-",
    markerfacecolor: Optional[str] = None,
) -> None:
    x = client_positions(aggregate["scaling_point"].to_numpy(dtype=int))
    means = aggregate[f"{metric}_mean"].to_numpy(dtype=float)
    facecolor = color if markerfacecolor is None else markerfacecolor

    ax.plot(
        x,
        means,
        color=color,
        linewidth=LINE_WIDTH,
        linestyle=linestyle,
        alpha=0.97,
        marker=marker,
        markersize=MARKER_SIZE,
        markerfacecolor=facecolor,
        markeredgecolor="white" if facecolor != "white" else color,
        markeredgewidth=MARKER_EDGE_WIDTH,
        zorder=3,
    )


def generic_run_legend(
    include_reference: bool = False,
    reference_label: str = "Validation recall requirement",
) -> List[Line2D]:
    handles = [
        Line2D(
            [0],
            [0],
            linestyle="none",
            marker="o",
            markersize=4.5,
            markerfacecolor=INDIVIDUAL_RUN_GRAY,
            markeredgecolor="white",
            markeredgewidth=0.35,
            alpha=0.65,
            label="Individual run",
        ),
        Line2D(
            [0],
            [0],
            color=SHARED_LEGEND_GRAY,
            linewidth=LINE_WIDTH,
            marker="o",
            markersize=4.5,
            markerfacecolor=SHARED_LEGEND_GRAY,
            markeredgecolor="white",
            markeredgewidth=MARKER_EDGE_WIDTH,
            label="Mean across runs",
        ),
    ]
    if include_reference:
        handles.append(
            Line2D(
                [0],
                [0],
                color=REFERENCE_GRAY,
                linewidth=1.0,
                linestyle="--",
                label=reference_label,
            )
        )
    return handles


def add_shared_legend(
    fig: plt.Figure,
    axes: Sequence[plt.Axes],
    handles: Sequence[Line2D],
    ncol: int,
) -> None:
    bottom_axis = axes[-1]
    position = bottom_axis.get_position()
    legend_x = position.x0 + position.width / 2

    fig.legend(
        handles=handles,
        loc="lower center",
        bbox_to_anchor=(legend_x, 0.018),
        ncol=ncol,
        frameon=True,
        framealpha=0.95,
        fontsize=9.2,
        borderaxespad=0.0,
        columnspacing=1.5,
        handlelength=2.4,
    )


def save_figure(
    fig: plt.Figure,
    output_dir: Path,
    stem: str,
    formats: Sequence[str],
) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)

    for fmt in formats:
        output_path = output_dir / f"{stem}.{fmt}"
        kwargs: Dict[str, Any] = {}
        if fmt == "png":
            kwargs["dpi"] = PNG_DPI
        elif fmt == "tiff":
            kwargs["dpi"] = PNG_DPI
            kwargs["pil_kwargs"] = {"compression": "tiff_lzw"}

        fig.savefig(output_path, format=fmt, **kwargs)
        print(f"  ✓ {output_path}")


# =============================================================================
# FIGURE 1: MCC-OPTIMAL OPERATING POINT
# =============================================================================
def plot_mcc_optimal(
    raw: pd.DataFrame,
    aggregate: pd.DataFrame,
    output_dir: Path,
    formats: Sequence[str],
    width: float,
) -> pd.DataFrame:
    regime_raw = raw[raw["threshold_regime"] == "mcc_optimal"].copy()
    regime_aggregate = aggregate[
        aggregate["threshold_regime"] == "mcc_optimal"
    ].sort_values("scaling_point").copy()

    clients = regime_aggregate["scaling_point"].astype(int).tolist()

    fig, axes = plt.subplots(
        3,
        1,
        figsize=(width, 8.4),
        sharex=True,
        constrained_layout=False,
    )
    fig.subplots_adjust(
        left=0.105,
        right=0.985,
        top=0.975,
        bottom=0.135,
        hspace=0.28,
    )

    # Panel A: validation-selected threshold.
    values_a = scatter_individual_runs(
        axes[0],
        regime_raw,
        clients,
        "selected_threshold",
    )
    plot_mean_line(
        axes[0],
        regime_aggregate,
        "selected_threshold",
        THRESHOLD_COLOR,
    )
    style_axis(axes[0])
    set_panel_label(axes[0], "A")
    axes[0].set_ylabel("Decision threshold")
    axes[0].yaxis.set_major_locator(MaxNLocator(nbins=5))
    axes[0].yaxis.set_major_formatter(trimmed_decimal_formatter(2))
    axes[0].set_ylim(
        *padded_limits(
            values_a,
            minimum_span=0.08,
            hard_bounds=(0.0, 1.0),
        )
    )
    set_client_axis(axes[0], clients, show_label=False)

    # Panel B: test MCC.
    values_b = scatter_individual_runs(
        axes[1],
        regime_raw,
        clients,
        "test_mcc",
    )
    plot_mean_line(
        axes[1],
        regime_aggregate,
        "test_mcc",
        MCC_COLOR,
    )
    style_axis(axes[1])
    set_panel_label(axes[1], "B")
    axes[1].set_ylabel("MCC")
    axes[1].yaxis.set_major_locator(MaxNLocator(nbins=5))
    axes[1].yaxis.set_major_formatter(trimmed_decimal_formatter(3))
    axes[1].set_ylim(
        *padded_limits(
            values_b,
            minimum_span=0.025,
            hard_bounds=(-1.0, 1.0),
        )
    )
    set_client_axis(axes[1], clients, show_label=False)

    # Panel C: test recall and specificity at each run's MCC-optimal point.
    recall_values = scatter_individual_runs(
        axes[2],
        regime_raw,
        clients,
        "test_recall",
        marker="o",
        jitter_offset=-0.025,
        facecolor=INDIVIDUAL_RUN_GRAY,
        alpha=0.58,
    )
    specificity_values = scatter_individual_runs(
        axes[2],
        regime_raw,
        clients,
        "test_specificity",
        marker="s",
        jitter_offset=0.025,
        facecolor=REFERENCE_GRAY,
        alpha=0.48,
    )
    plot_mean_line(
        axes[2],
        regime_aggregate,
        "test_recall",
        RECALL_COLOR,
        marker="o",
        linestyle="-",
    )
    plot_mean_line(
        axes[2],
        regime_aggregate,
        "test_specificity",
        SPECIFICITY_COLOR,
        marker="s",
        linestyle="--",
        markerfacecolor="white",
    )
    style_axis(axes[2])
    set_panel_label(axes[2], "C")
    axes[2].set_ylabel("recall and specificity")
    axes[2].yaxis.set_major_locator(MaxNLocator(nbins=5))
    axes[2].yaxis.set_major_formatter(trimmed_decimal_formatter(2))
    axes[2].set_ylim(
        *padded_limits(
            recall_values + specificity_values,
            minimum_span=0.10,
            hard_bounds=(0.0, 1.0),
        )
    )
    set_client_axis(axes[2], clients, show_label=True)

    metric_handles = [
        Line2D(
            [0],
            [0],
            color=RECALL_COLOR,
            linewidth=LINE_WIDTH,
            linestyle="-",
            marker="o",
            markersize=4.5,
            markerfacecolor=RECALL_COLOR,
            markeredgecolor="white",
            label="Recall",
        ),
        Line2D(
            [0],
            [0],
            color=SPECIFICITY_COLOR,
            linewidth=LINE_WIDTH,
            linestyle="--",
            marker="s",
            markersize=4.5,
            markerfacecolor="white",
            markeredgecolor=SPECIFICITY_COLOR,
            label="Specificity",
        ),
    ]
    axes[2].legend(
        handles=metric_handles,
        loc="best",
        frameon=False,
        fontsize=9.2,
    )

    add_shared_legend(
        fig,
        axes,
        generic_run_legend(),
        ncol=2,
    )

    save_figure(
        fig,
        output_dir,
        "figure_1_mcc_optimal_operating_point",
        formats,
    )
    plt.close(fig)

    columns = [
        "strategy",
        "threshold_regime",
        "scaling_point",
        "n_runs",
        "selected_threshold_mean",
        "selected_threshold_std",
        "test_mcc_mean",
        "test_mcc_std",
        "test_recall_mean",
        "test_recall_std",
        "test_specificity_mean",
        "test_specificity_std",
    ]
    return regime_aggregate[
        [column for column in columns if column in regime_aggregate.columns]
    ]


# =============================================================================
# FIGURE 2: FIXED MINIMUM-RECALL OPERATING POINT
# =============================================================================
def plot_minimum_recall(
    raw: pd.DataFrame,
    aggregate: pd.DataFrame,
    minimum_recall: float,
    output_dir: Path,
    formats: Sequence[str],
    width: float,
) -> pd.DataFrame:
    regime_raw = raw[raw["threshold_regime"] == "minimum_recall"].copy()
    regime_aggregate = aggregate[
        aggregate["threshold_regime"] == "minimum_recall"
    ].sort_values("scaling_point").copy()

    clients = regime_aggregate["scaling_point"].astype(int).tolist()

    fig, axes = plt.subplots(
        2,
        1,
        figsize=(width, 6.1),
        sharex=True,
        constrained_layout=False,
    )
    fig.subplots_adjust(
        left=0.105,
        right=0.985,
        top=0.970,
        bottom=0.175,
        hspace=0.30,
    )

    # Panel A: validation-selected threshold.
    values_a = scatter_individual_runs(
        axes[0],
        regime_raw,
        clients,
        "selected_threshold",
    )
    plot_mean_line(
        axes[0],
        regime_aggregate,
        "selected_threshold",
        THRESHOLD_COLOR,
    )
    style_axis(axes[0])
    set_panel_label(axes[0], "A")
    axes[0].set_ylabel("Decision threshold")
    axes[0].yaxis.set_major_locator(MaxNLocator(nbins=5))
    axes[0].yaxis.set_major_formatter(trimmed_decimal_formatter(2))
    axes[0].set_ylim(
        *padded_limits(
            values_a,
            minimum_span=0.08,
            hard_bounds=(0.0, 1.0),
        )
    )
    set_client_axis(axes[0], clients, show_label=False)

    # Panel B: test recall and specificity after transferring the same
    # validation-selected threshold to the test set.
    recall_values = scatter_individual_runs(
        axes[1],
        regime_raw,
        clients,
        "test_recall",
        marker="o",
        jitter_offset=-0.025,
        facecolor=INDIVIDUAL_RUN_GRAY,
        alpha=0.58,
    )
    specificity_values = scatter_individual_runs(
        axes[1],
        regime_raw,
        clients,
        "test_specificity",
        marker="s",
        jitter_offset=0.025,
        facecolor=REFERENCE_GRAY,
        alpha=0.48,
    )
    plot_mean_line(
        axes[1],
        regime_aggregate,
        "test_recall",
        RECALL_COLOR,
        marker="o",
        linestyle="-",
    )
    plot_mean_line(
        axes[1],
        regime_aggregate,
        "test_specificity",
        SPECIFICITY_COLOR,
        marker="s",
        linestyle="--",
        markerfacecolor="white",
    )
    axes[1].axhline(
        minimum_recall,
        color=REFERENCE_GRAY,
        linewidth=1.0,
        linestyle=":",
        zorder=1,
    )
    style_axis(axes[1])
    set_panel_label(axes[1], "B")
    axes[1].set_ylabel("Recall and specificity")
    axes[1].yaxis.set_major_locator(MaxNLocator(nbins=5))
    axes[1].yaxis.set_major_formatter(trimmed_decimal_formatter(2))
    axes[1].set_ylim(
        *padded_limits(
            recall_values + specificity_values,
            minimum_span=0.10,
            include_value=minimum_recall,
            hard_bounds=(0.0, 1.0),
        )
    )
    set_client_axis(axes[1], clients, show_label=True)

    metric_handles = [
        Line2D(
            [0],
            [0],
            color=RECALL_COLOR,
            linewidth=LINE_WIDTH,
            linestyle="-",
            marker="o",
            markersize=4.5,
            markerfacecolor=RECALL_COLOR,
            markeredgecolor="white",
            label="Recall",
        ),
        Line2D(
            [0],
            [0],
            color=SPECIFICITY_COLOR,
            linewidth=LINE_WIDTH,
            linestyle="--",
            marker="s",
            markersize=4.5,
            markerfacecolor="white",
            markeredgecolor=SPECIFICITY_COLOR,
            label="Specificity",
        ),
        Line2D(
            [0],
            [0],
            color=REFERENCE_GRAY,
            linewidth=1.0,
            linestyle=":",
            label=f"Validation recall requirement ({minimum_recall:.2f})",
        ),
    ]
    axes[1].legend(
        handles=metric_handles,
        loc="best",
        frameon=False,
        fontsize=9.2,
    )

    add_shared_legend(
        fig,
        axes,
        generic_run_legend(),
        ncol=2,
    )

    save_figure(
        fig,
        output_dir,
        "figure_2_fixed_recall_operating_point",
        formats,
    )
    plt.close(fig)

    columns = [
        "strategy",
        "threshold_regime",
        "scaling_point",
        "n_runs",
        "selected_threshold_mean",
        "selected_threshold_std",
        "test_recall_mean",
        "test_recall_std",
        "test_specificity_mean",
        "test_specificity_std",
        "test_false_positive_rate_mean",
        "test_false_positive_rate_std",
        "test_false_positives_per_1000_negatives_mean",
        "test_false_positives_per_1000_negatives_std",
    ]
    return regime_aggregate[
        [column for column in columns if column in regime_aggregate.columns]
    ]


# =============================================================================
# CAPTIONS
# =============================================================================
def write_captions(
    output_dir: Path,
    minimum_recall: float,
    expected_runs: int,
) -> Path:
    path = output_dir / "suggested_threshold_dependent_figure_captions.txt"
    text = f"""Suggested APA-style figure captions
===================================

Figure X
Threshold-Dependent SCAFFOLD Test Performance at the MCC-Optimal Operating Point

Note. For each run, the checkpoint with the highest validation average precision was selected before threshold optimization. The decision threshold was then selected by maximizing MCC over all distinct operating points induced by the validation scores and transferred unchanged to the test set. Panel A shows the validation-selected threshold, Panel B shows test MCC, and Panel C shows test recall and specificity at the corresponding MCC-optimal operating point. Small gray points represent individual runs; colored markers and connecting lines represent means across {expected_runs} repeated runs. In Panel C, solid circles represent recall and dashed open squares represent specificity. Recall and specificity in Panel C characterize separately optimized operating points and are therefore not standardized across scaling configurations. The client axis is logarithmic to base 2. Restricted panel-specific y-axis ranges make small differences visible.

Figure X
Threshold-Dependent SCAFFOLD Test Performance Under a Fixed Validation Recall Requirement

Note. For each run, the checkpoint with the highest validation average precision was selected before threshold optimization. Among all distinct operating points induced by the validation scores that satisfied recall >= {minimum_recall:.2f}, the threshold yielding the highest validation specificity was selected and transferred unchanged to the test set. Panel A shows the validation-selected threshold, and Panel B jointly shows test recall and specificity at the transferred operating point. The dotted horizontal line in Panel B denotes the prespecified validation recall requirement; test recall is shown because the constraint was imposed on the validation set rather than the test set. Small gray circles and squares represent individual-run recall and specificity values, respectively; colored markers and connecting lines represent means across {expected_runs} repeated runs. Solid circles represent recall and dashed open squares represent specificity. The client axis is logarithmic to base 2. Restricted panel-specific y-axis ranges make small differences visible.
"""
    path.write_text(text, encoding="utf-8")
    return path


# =============================================================================
# MAIN
# =============================================================================
def main() -> None:
    args = parse_args()
    font_name = available_font(args.font)
    configure_matplotlib(font_name)

    print("=" * 82)
    print("APA-STYLE THRESHOLD-DEPENDENT SCAFFOLD FIGURES")
    print(f"Input     : {args.input}")
    print(f"Output    : {args.output_dir}")
    print(f"Strategy  : {args.strategy}")
    print(f"Font      : {font_name}")
    print(f"Formats   : {', '.join(args.formats)}")
    print("=" * 82)

    raw = read_input(args.input)
    raw = normalize_and_validate(
        raw,
        strategy=args.strategy,
        expected_runs=args.expected_runs,
        expected_scaling_points=args.expected_scaling_points,
    )
    aggregate = aggregate_results(raw)
    minimum_recall = get_minimum_recall_requirement(raw)

    args.output_dir.mkdir(parents=True, exist_ok=True)

    raw_path = args.output_dir / "threshold_dependent_run_results.csv"
    aggregate_path = args.output_dir / "threshold_dependent_aggregate.csv"
    raw.to_csv(raw_path, index=False)
    aggregate.to_csv(aggregate_path, index=False)

    figure_1_table = plot_mcc_optimal(
        raw=raw,
        aggregate=aggregate,
        output_dir=args.output_dir,
        formats=args.formats,
        width=args.width,
    )
    figure_1_path = args.output_dir / "figure_1_mcc_optimal_values.csv"
    figure_1_table.to_csv(figure_1_path, index=False)

    figure_2_table = plot_minimum_recall(
        raw=raw,
        aggregate=aggregate,
        minimum_recall=minimum_recall,
        output_dir=args.output_dir,
        formats=args.formats,
        width=args.width,
    )
    figure_2_path = args.output_dir / "figure_2_fixed_recall_values.csv"
    figure_2_table.to_csv(figure_2_path, index=False)

    caption_path = write_captions(
        output_dir=args.output_dir,
        minimum_recall=minimum_recall,
        expected_runs=args.expected_runs,
    )

    print()
    print("Finished. Main outputs:")
    print("  Figure 1: MCC-optimal operating point")
    print("  Figure 2: fixed minimum-recall operating point")
    print(f"  Run data : {raw_path}")
    print(f"  Aggregate: {aggregate_path}")
    print(f"  Figure 1 data: {figure_1_path}")
    print(f"  Figure 2 data: {figure_2_path}")
    print(f"  Captions : {caption_path}")
    print("=" * 82)


if __name__ == "__main__":
    main()
